sonar.organization=sorimdevs-tech
sonar.projectKey=sorimdevs-tech_QlikSense
sonar.projectName=QlikSense
sonar.sources=qlik_app/converter/csv/src,qlik_app/qlik/qlik-fastapi-backend
sonar.exclusions=**/node_modules/**,**/__pycache__/**
sonar.python.version=3.11
