"""
M Query File Generator Module (Production Ready)

Generates Power BI M Query files in multiple formats:
- .pq  (Power Query format)
- .m   (Standard M file)
- .txt (Documentation format)
- .zip (Bundle containing all formats)

Designed to work with SimpleMQueryGenerator output.
No fake placeholders. No invalid M syntax.
"""

import logging
from typing import Dict, Any
from datetime import datetime
import io
import zipfile

logger = logging.getLogger(__name__)


class MQueryFileGenerator:
    """
    Generate downloadable Power BI M Query files.
    Accepts fully generated M Query string (from SimpleMQueryGenerator).
    """

    def __init__(self, m_query: str, parsed_script: Dict[str, Any] = None):
        self.m_query = m_query.strip()
        self.parsed_script = parsed_script or {}
        self.summary = self.parsed_script.get("summary", {})

    # ============================================================
    # .PQ FILE
    # ============================================================

    def generate_pq_content(self) -> str:
        """Generate .pq file content (Power Query compatible)"""

        header = (
            "// ============================================================\n"
            "// Power BI M Query\n"
            "// Converted from Qlik LoadScript\n"
            f"// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
            "// ============================================================\n\n"
        )

        return header + self.m_query

    # ============================================================
    # .M FILE
    # ============================================================

    def generate_m_content(self) -> str:
        """Generate standard .m file content"""
        return self.m_query

    # ============================================================
    # .TXT FILE (Documentation)
    # ============================================================

    def generate_txt_content(self) -> str:
        """Generate documentation-friendly .txt file"""

        metadata = (
            "=" * 80 + "\n"
            "POWER BI M QUERY DOCUMENTATION\n"
            + "=" * 80 + "\n\n"
        )

        if self.summary:
            metadata += "SCRIPT SUMMARY:\n"
            metadata += f"  Tables: {self.summary.get('tables_count', 0)}\n"
            metadata += f"  Fields: {self.summary.get('fields_count', 0)}\n"
            metadata += f"  Data Connections: {self.summary.get('connections_count', 0)}\n"
            metadata += f"  Transformations: {self.summary.get('transformations_count', 0)}\n"
            metadata += f"  Joins: {self.summary.get('joins_count', 0)}\n\n"

        metadata += (
            "HOW TO USE:\n"
            "1. Open Power BI Desktop\n"
            "2. Click: Home → Transform Data → Advanced Editor\n"
            "3. Replace existing code with the M Query below\n"
            "4. Click Done\n\n"
            + "=" * 80 + "\n"
            "M QUERY CODE\n"
            + "=" * 80 + "\n\n"
        )

        return metadata + self.m_query

    # ============================================================
    # EXTRACT INDIVIDUAL TABLE BLOCKS (REAL SPLIT)
    # ============================================================

    def split_tables_from_mquery(self) -> Dict[str, str]:
        """
        Split multi-table M Query (generated by SimpleMQueryGenerator)
        into individual table query blocks.

        Works only if generator output contains:
        // ===== TABLE: TableName =====
        """

        logger.info("Splitting tables from generated M Query...")

        table_blocks = {}
        lines = self.m_query.splitlines()

        current_table = None
        current_buffer = []

        for line in lines:
            if line.strip().startswith("// ===== TABLE:"):
                # Save previous table
                if current_table and current_buffer:
                    table_blocks[current_table] = "\n".join(current_buffer).strip()
                    current_buffer = []

                current_table = line.replace("// ===== TABLE:", "").strip()
                continue

            if current_table:
                current_buffer.append(line)

        # Save last table
        if current_table and current_buffer:
            table_blocks[current_table] = "\n".join(current_buffer).strip()

        logger.info(f"✅ Extracted {len(table_blocks)} table block(s)")
        return table_blocks

    # ============================================================
    # FILE DOWNLOAD STRUCTURE
    # ============================================================

    def get_file_downloads(self) -> Dict[str, Dict[str, str]]:
        """Return all supported file formats"""

        return {
            "pq": {
                "filename": "powerbi_query.pq",
                "content": self.generate_pq_content(),
                "mime_type": "text/plain",
            },
            "m": {
                "filename": "powerbi_query.m",
                "content": self.generate_m_content(),
                "mime_type": "text/plain",
            },
            "txt": {
                "filename": "powerbi_query_documentation.txt",
                "content": self.generate_txt_content(),
                "mime_type": "text/plain",
            },
        }


# ============================================================
# ZIP GENERATOR
# ============================================================

def generate_dual_download_zip(m_query: str, parsed_script: Dict[str, Any] = None) -> bytes:
    """
    Create ZIP package containing:
    - .pq
    - .m
    - .txt
    """

    logger.info("Creating ZIP package with .pq, .m, .txt")

    generator = MQueryFileGenerator(m_query, parsed_script)
    files = generator.get_file_downloads()

    zip_buffer = io.BytesIO()

    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for file_info in files.values():
            zip_file.writestr(file_info["filename"], file_info["content"])

    zip_buffer.seek(0)

    logger.info(f"✅ ZIP created ({len(zip_buffer.getvalue())} bytes)")
    return zip_buffer.getvalue()